mkdir "St Philip's Cathedral, Birmingham"
mkdir "Blackburn Cathedral"
mkdir "Bradford Cathedral"
mkdir "Bristol Cathedral"
mkdir "Canterbury Cathedral"
mkdir "Carlisle Cathedral"
mkdir "Chelmsford Cathedral"
mkdir "Chester Cathedral"
mkdir "Chichester Cathedral"
mkdir "Coventry Cathedral"
mkdir "Derby Cathedral"
mkdir "Durham Cathedral"
mkdir "Ely Cathedral"
mkdir "Exeter Cathedral"
mkdir "Gloucester Cathedral"
mkdir "Guildford Cathedral"
mkdir "Hereford Cathedral"
mkdir "Leicester Cathedral"
mkdir "Lichfield Cathedral"
mkdir "Lincoln Cathedral"
mkdir "Liverpool Anglican Cathedral"
mkdir "St. Paul's Cathedral"
mkdir "Manchester Cathedral"
mkdir "St Nicholas' Cathedral, Newcastle upon Tyne"
mkdir "Norwich Cathedral"
mkdir "Christ Church Cathedral, Oxford"
mkdir "Peterborough Cathedral"
mkdir "Portsmouth Cathedral"
mkdir "Ripon Cathedral"
mkdir "Rochester Cathedral"
mkdir "St Albans Cathedral"
mkdir "Salisbury Cathedral"
mkdir "Sheffield Cathedral"
mkdir "Southwark Cathedral"
mkdir "Southwell Minster"
mkdir "St Edmundsbury Cathedral"
mkdir "Truro Cathedral"
mkdir "Wakefield Cathedral"
mkdir "Wells Cathedral"
mkdir "Winchester Cathedral"
mkdir "Worcester Cathedral"
mkdir "York Minster"
